Add scenario test for workload version
canonical/traefik-k8s-operator pull request #172
Opened 2023-05-03 12:59 UTC by sed-i

This PR adds a scenario test around `set_workload_version`.

2023-05-09 08:54 UTC, PietroPasotti requested changes
Could you bump the scenario version to 3.0? that will have `State.status.workload_version` (and some more breaking changes)

2023-05-09 13:44 UTC, sed-i commented
> Could you bump the scenario version to 3.0? that will have `State.status.workload_version` (and some more breaking changes)

Done

2023-05-09 14:17 UTC, PietroPasotti requested changes
[full disclosure] I tried doing the explicit tagging comments thing we discussed. Let's see if it works!

2023-05-09 15:06 UTC, sed-i commented on tests/scenario/test_workload_version.py
> +        out = Context(charm_type=TraefikIngressCharm).run("start", self.state)
Done in next commit.

2023-05-09 15:06 UTC, sed-i commented on tests/scenario/test_workload_version.py
> +class TestWorkloadVersion(unittest.TestCase):
That's a tough one.
The entire charming ecosystem is unittest for utests and pytest for itests.

On one hand, one may argue traefik should too use unittest for utest.
On the other hand, scenario tests could be considered separately from utests, and the testing framework of choice for those is not yet established.

2023-06-06 13:33 UTC, PietroPasotti commented on tests/scenario/test_workload_version.py
> +class TestWorkloadVersion(unittest.TestCase):
scenario exposes a pytest plugin, and I've not yet seen unittest + scenario in action, so yeah, still TBD but if it were up to me you know what I'd pick :)

2023-06-06 21:36 UTC, sed-i commented on tests/scenario/test_workload_version.py
> +class TestWorkloadVersion(unittest.TestCase):
Thanks! Captured in https://github.com/canonical/traefik-k8s-operator/issues/185.

2023-06-07 08:18 UTC, merged