Charm cleanup
canonical/traefik-k8s-operator pull request #67
Opened 2022-07-04 08:42 UTC by PietroPasotti

NOTE: Wait on #63 merge before reviewing.

## Issue
Simplify and cleanup charm.py now that
1) IPA and IPU interfaces are unified (cf. #63)
2) Harness bug https://github.com/canonical/operator/issues/694 is fixed

## Testing Instructions
Updated one test to guard against regressions of point 2 above
No behavioral / public API changes.

## Release Notes
- Cleaned up Traefik charm internals

2022-07-04 12:36 UTC, simskij approved these changes

2022-07-05 09:15 UTC, simskij requested changes

2022-07-05 09:17 UTC, PietroPasotti commented on tests/integration/conftest.py
> +    )
ah something got lost when rebasing. I'd deleted that.

2022-07-05 10:42 UTC, jnsgruk approved these changes

2022-07-05 12:51 UTC, simskij approved these changes

2022-07-05 13:08 UTC, merged